version: "3.8"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otelcol/config.yml"]
    restart: unless-stopped
    volumes:
      - ./otel-collector/otel-collector-config.yml:/etc/otelcol/config.yml
    ports:
      - "4319:4319"
      - "9465:9465"
    depends_on:
      - loki
    cpus: "0.30"
    mem_limit: 256m

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    cpus: "0.50"
    mem_limit: 512m
    networks:
      - events-backend
      - payments-net

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    cpus: "0.50"
    mem_limit: 512m

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail-config.yml
    cpus: "0.20"
    mem_limit: 128m

volumes:
  prometheus-data:
  loki-data:

networks:
  payments-net:
    external: true

  events-backend:
    external: true