global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-gateway-hml"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: 
          - host.docker.internal:8080

  - job_name: "api-payments-hml"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: 
          - host.docker.internal:8083

  - job_name: "api-gateway-prod"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: 
          - 192.168.1.54:8080

  - job_name: "api-payments-prod"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: 
          - 192.168.1.54:8083

  - job_name: "windows_collector"
    static_configs:
      - targets:
          - "host.docker.internal:10243"

        